/* =====================================================================
   01_esquema.sql
   Proyecto: Inventario Distribuido de Accesorios para Mascotas
   Destino : Neon (PostgreSQL 16+)

   EJECUTAR EN LAS 4 BASES:
       bd_central, bd_monterrey, bd_puebla, bd_queretaro

   El script es IDÉNTICO para las cuatro y es idempotente (se puede
   correr varias veces). Ninguna base necesita ajustes propios: el
   modelo guarda las cuatro sucursales en cada base y toda consulta
   se filtra por SucursalID — igual que hacía la replicación de mezcla
   de SQL Server, que dejaba una copia completa en cada sitio.

   ---------------------------------------------------------------------
   NOTAS DE MIGRACIÓN SQL SERVER -> POSTGRESQL
   ---------------------------------------------------------------------
   Esquema  dbo              se conserva (CREATE SCHEMA dbo) para no
                             reescribir las referencias dbo.Tabla del
                             código PHP.
   Identificadores           van ENTRECOMILLADOS ("ProductoID"). Postgres
                             pasa a minúsculas todo identificador sin
                             comillas; entrecomillar conserva el
                             PascalCase original y, con él, las claves
                             de los arreglos que devuelve PDO
                             ($fila['ProductoID'] sigue funcionando).
   INT IDENTITY(1,1)      -> INTEGER GENERATED BY DEFAULT AS IDENTITY
   NVARCHAR(n)            -> VARCHAR(n)
   DATETIME2(0)           -> TIMESTAMP(0)
   BIT                    -> SMALLINT 0/1  (NO boolean: PDO devuelve el
                             boolean de Postgres como la cadena 'f', que
                             en PHP es VERDADERA; con 0/1 la lógica
                             existente ->  if ($fila['Activo'])  sigue
                             siendo correcta)
   DECIMAL(18,2)          -> NUMERIC(18,2)
   SYSDATETIME()          -> dbo.ahora()  (hora local de México)
   rowguid / ROWGUIDCOL   -> se eliminan: eran exigencia de la
                             replicación de mezcla, no del modelo.
   Índice filtrado        -> índice parcial (WHERE ...), equivalente.
   ===================================================================== */

CREATE SCHEMA IF NOT EXISTS dbo;

SET search_path TO dbo, public;


/* =====================================================================
   PARTE 0 — RELOJ DE LA APLICACIÓN

   Reemplaza a SYSDATETIME(). Neon corre en UTC; el negocio opera en
   México. Sin esto, el corte "ventas de hoy" cambiaría de día a las
   18:00 hora local.
   ===================================================================== */
CREATE OR REPLACE FUNCTION dbo.ahora()
RETURNS TIMESTAMP(0)
LANGUAGE sql
STABLE
AS $$
    SELECT (NOW() AT TIME ZONE 'America/Mexico_City')::timestamp(0);
$$;

COMMENT ON FUNCTION dbo.ahora() IS
    'Fecha y hora local del negocio. Sustituye a SYSDATETIME() de SQL Server.';


/* =====================================================================
   PARTE 1 — CATÁLOGOS BASE
   ===================================================================== */

/* ---------------------------------------------------------------------
   Sucursales — las 4 sedes. Los ID son fijos (no IDENTITY) porque el
   código y la configuración los referencian por número:
       1 = Central   2 = Monterrey   3 = Puebla   4 = Querétaro
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo."Sucursales"
(
    "SucursalID"  INTEGER      NOT NULL,
    "Nombre"      VARCHAR(80)  NOT NULL,
    "Ciudad"      VARCHAR(80)      NULL,
    "Direccion"   VARCHAR(200)     NULL,
    "Telefono"    VARCHAR(30)      NULL,

    -- Marca la sede que surte a las demás. Los procedimientos la
    -- localizan por aquí, nunca por el número 1 escrito a mano.
    "EsCentral"   SMALLINT     NOT NULL DEFAULT 0,

    CONSTRAINT "PK_Sucursales"      PRIMARY KEY ("SucursalID"),
    CONSTRAINT "CK_Suc_EsCentral"   CHECK ("EsCentral" IN (0, 1))
);

/* Sólo puede haber una Central. */
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Suc_UnaCentral"
    ON dbo."Sucursales" ("EsCentral")
    WHERE "EsCentral" = 1;


/* ---------------------------------------------------------------------
   Categorias — collares, alimento, juguetes, higiene, ...
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo."Categorias"
(
    "CategoriaID"  INTEGER      NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nombre"       VARCHAR(80)  NOT NULL,
    "Descripcion"  VARCHAR(200)     NULL,

    CONSTRAINT "PK_Categorias"  PRIMARY KEY ("CategoriaID"),
    CONSTRAINT "UQ_Cat_Nombre"  UNIQUE ("Nombre")
);


/* ---------------------------------------------------------------------
   Proveedores — de quién llega la mercancía al almacén central.
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo."Proveedores"
(
    "ProveedorID"  INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nombre"       VARCHAR(120)  NOT NULL,
    "Contacto"     VARCHAR(120)      NULL,
    "Telefono"     VARCHAR(30)       NULL,
    "Correo"       VARCHAR(120)      NULL,

    CONSTRAINT "PK_Proveedores"  PRIMARY KEY ("ProveedorID"),
    CONSTRAINT "UQ_Prov_Nombre"  UNIQUE ("Nombre")
);


/* ---------------------------------------------------------------------
   Productos — catálogo maestro. Sólo Central lo escribe.

   La baja es SIEMPRE lógica ("Activo" = 0): hay referencias vivas desde
   Movimientos, DetalleVenta e InventarioSucursal.
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo."Productos"
(
    "ProductoID"      INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nombre"          VARCHAR(150)   NOT NULL,
    "CategoriaID"     INTEGER        NOT NULL,
    "ProveedorID"     INTEGER            NULL,
    "TipoMascota"     VARCHAR(10)    NOT NULL DEFAULT 'Ambos',
    "Marca"           VARCHAR(80)        NULL,
    "Talla"           VARCHAR(30)        NULL,
    "PrecioUnitario"  NUMERIC(18,2)  NOT NULL,

    -- Punto de reorden del catálogo. El que gobierna la alerta es el de
    -- InventarioSucursal; éste sólo siembra el valor inicial.
    "StockMinimo"     INTEGER        NOT NULL DEFAULT 5,
    "Activo"          SMALLINT       NOT NULL DEFAULT 1,

    CONSTRAINT "PK_Productos"        PRIMARY KEY ("ProductoID"),
    CONSTRAINT "FK_Prod_Categoria"   FOREIGN KEY ("CategoriaID")
        REFERENCES dbo."Categorias" ("CategoriaID"),
    CONSTRAINT "FK_Prod_Proveedor"   FOREIGN KEY ("ProveedorID")
        REFERENCES dbo."Proveedores" ("ProveedorID"),
    CONSTRAINT "CK_Prod_Tipo"        CHECK ("TipoMascota" IN ('Perro', 'Gato', 'Ambos')),
    CONSTRAINT "CK_Prod_Precio"      CHECK ("PrecioUnitario" >= 0),
    CONSTRAINT "CK_Prod_Minimo"      CHECK ("StockMinimo" >= 0),
    CONSTRAINT "CK_Prod_Activo"      CHECK ("Activo" IN (0, 1))
);

CREATE INDEX IF NOT EXISTS "IX_Prod_Nombre"    ON dbo."Productos" ("Nombre");
CREATE INDEX IF NOT EXISTS "IX_Prod_Categoria" ON dbo."Productos" ("CategoriaID");


/* ---------------------------------------------------------------------
   Empleados — también son los usuarios de la aplicación.

   "PasswordHash" guarda el resultado de password_hash() de PHP (bcrypt,
   60 caracteres). Se dimensiona a 255 para admitir algoritmos futuros,
   tal como hacía sql/01_Ajustes_Usuarios.sql en SQL Server.
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo."Empleados"
(
    "EmpleadoID"     INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Nombre"         VARCHAR(120)  NOT NULL,
    "Puesto"         VARCHAR(80)       NULL,
    "SucursalID"     INTEGER       NOT NULL,
    "NombreUsuario"  VARCHAR(50)   NOT NULL,
    "PasswordHash"   VARCHAR(255)  NOT NULL,
    "Rol"            VARCHAR(20)   NOT NULL DEFAULT 'Vendedor',
    "Activo"         SMALLINT      NOT NULL DEFAULT 1,

    CONSTRAINT "PK_Empleados"     PRIMARY KEY ("EmpleadoID"),
    CONSTRAINT "UQ_Emp_Usuario"   UNIQUE ("NombreUsuario"),
    CONSTRAINT "FK_Emp_Sucursal"  FOREIGN KEY ("SucursalID")
        REFERENCES dbo."Sucursales" ("SucursalID"),
    CONSTRAINT "CK_Emp_Rol"       CHECK ("Rol" IN ('Admin', 'Vendedor')),
    CONSTRAINT "CK_Emp_Activo"    CHECK ("Activo" IN (0, 1))
);

CREATE INDEX IF NOT EXISTS "IX_Emp_Sucursal" ON dbo."Empleados" ("SucursalID");


/* =====================================================================
   PARTE 2 — INVENTARIO PARTICIONADO POR SUCURSAL

   Ésta es la corrección de fondo del diseño original: la tabla vieja
   dbo.Inventario tenía como llave primaria SÓLO ProductoID, así que las
   cuatro sedes escribían LA MISMA FILA y en cada sincronización el stock
   de tres de ellas se perdía.

   Con PK (SucursalID, ProductoID) cada sitio escribe únicamente filas
   que le pertenecen:

       *** CADA SITIO ESCRIBE SOLAMENTE LAS FILAS QUE LE PERTENECEN ***

   La tabla vieja dbo.Inventario NO se reconstruye aquí: era el objeto
   defectuoso que esta migración vino a reemplazar.
   ===================================================================== */
CREATE TABLE IF NOT EXISTS dbo."InventarioSucursal"
(
    "SucursalID"           INTEGER       NOT NULL,
    "ProductoID"           INTEGER       NOT NULL,
    "Stock"                INTEGER       NOT NULL DEFAULT 0,

    -- Punto de reorden. El requerimiento pide alerta con <= 5 unidades;
    -- se deja como columna para poder afinarlo por producto y sucursal.
    "StockMinimo"          INTEGER       NOT NULL DEFAULT 5,

    -- Hasta cuánto se quiere reabastecer al dispararse la alerta.
    "StockObjetivo"        INTEGER       NOT NULL DEFAULT 20,

    "UltimaActualizacion"  TIMESTAMP(0)  NOT NULL DEFAULT dbo.ahora(),

    CONSTRAINT "PK_InventarioSucursal" PRIMARY KEY ("SucursalID", "ProductoID"),

    CONSTRAINT "FK_InvSuc_Sucursal" FOREIGN KEY ("SucursalID")
        REFERENCES dbo."Sucursales" ("SucursalID"),
    CONSTRAINT "FK_InvSuc_Producto" FOREIGN KEY ("ProductoID")
        REFERENCES dbo."Productos" ("ProductoID"),

    -- Red de seguridad: ninguna ruta de código puede dejar stock negativo.
    CONSTRAINT "CK_InvSuc_StockNoNegativo" CHECK ("Stock" >= 0),
    CONSTRAINT "CK_InvSuc_Minimos"         CHECK ("StockMinimo" >= 0
                                             AND "StockObjetivo" >= "StockMinimo")
);

/* SucursalID va primero en la PK (particiona por sitio); este índice
   cubre la consulta inversa que usa Central: "stock de un producto en
   todas las sucursales". */
CREATE INDEX IF NOT EXISTS "IX_InvSuc_Producto"
    ON dbo."InventarioSucursal" ("ProductoID") INCLUDE ("Stock");

/* Barrido de alertas y tablero de stock bajo. */
CREATE INDEX IF NOT EXISTS "IX_InvSuc_Alerta"
    ON dbo."InventarioSucursal" ("SucursalID")
    WHERE "Stock" <= "StockMinimo";


/* =====================================================================
   PARTE 3 — SOLICITUDES DE STOCK (requisiciones)

   MÁQUINA DE ESTADOS (y quién escribe en cada paso):

     [Sucursal] inserta ................................. PENDIENTE
          |                                                  |
          |                                    [Central] ofrece cantidad
          |                                    (total o parcial) y DESCUENTA
          |                                     su propio stock ....> OFERTADO
          |                                                  |
          |                      [Sucursal] responde  +------+------+
          |                                           |             |
          |                                       ACEPTADO      RECHAZADO
          |                                    (suma su stock)  (Central
          |                                                     reintegra)
     [Central] envía directo (sin solicitud previa) ......> OFERTADO

   En ningún momento dos sitios escriben la fila a la vez: el turno se
   pasa junto con el estado.
   ===================================================================== */
CREATE TABLE IF NOT EXISTS dbo."SolicitudesStock"
(
    "SolicitudID"         INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY,

    "SucursalID"          INTEGER       NOT NULL,  -- sucursal que pide (dueña de la fila)
    "ProductoID"          INTEGER       NOT NULL,

    "CantidadSolicitada"  INTEGER       NOT NULL,
    "CantidadOfrecida"    INTEGER           NULL,  -- NULL mientras esté PENDIENTE

    "Estado"              VARCHAR(20)   NOT NULL DEFAULT 'PENDIENTE',

    -- AUTOMATICA   : la disparó el trigger de stock bajo
    -- MANUAL       : la capturó el encargado de la sucursal
    -- ENVIO_CENTRAL: Central empujó mercancía sin que se la pidieran
    "Origen"              VARCHAR(20)   NOT NULL DEFAULT 'MANUAL',

    "StockAlSolicitar"    INTEGER           NULL,  -- foto del stock que disparó la alerta
    "ComentarioCentral"   VARCHAR(300)      NULL,
    "ComentarioSucursal"  VARCHAR(300)      NULL,

    "EmpleadoSolicitaID"  INTEGER           NULL,
    "EmpleadoAtiendeID"   INTEGER           NULL,

    "FechaSolicitud"      TIMESTAMP(0)  NOT NULL DEFAULT dbo.ahora(),
    "FechaOferta"         TIMESTAMP(0)      NULL,
    "FechaRespuesta"      TIMESTAMP(0)      NULL,

    -- Cuando la sucursal rechaza, el stock que Central ya había apartado
    -- tiene que volver a Central. Esta bandera evita reintegrarlo dos veces.
    "StockReintegrado"    SMALLINT      NOT NULL DEFAULT 0,

    CONSTRAINT "PK_SolicitudesStock" PRIMARY KEY ("SolicitudID"),

    CONSTRAINT "FK_Sol_Sucursal" FOREIGN KEY ("SucursalID")
        REFERENCES dbo."Sucursales" ("SucursalID"),
    CONSTRAINT "FK_Sol_Producto" FOREIGN KEY ("ProductoID")
        REFERENCES dbo."Productos" ("ProductoID"),
    CONSTRAINT "FK_Sol_EmpSolicita" FOREIGN KEY ("EmpleadoSolicitaID")
        REFERENCES dbo."Empleados" ("EmpleadoID"),
    CONSTRAINT "FK_Sol_EmpAtiende" FOREIGN KEY ("EmpleadoAtiendeID")
        REFERENCES dbo."Empleados" ("EmpleadoID"),

    CONSTRAINT "CK_Sol_Estado" CHECK ("Estado" IN ('PENDIENTE', 'OFERTADO', 'ACEPTADO', 'RECHAZADO')),
    CONSTRAINT "CK_Sol_Origen" CHECK ("Origen" IN ('AUTOMATICA', 'MANUAL', 'ENVIO_CENTRAL')),
    CONSTRAINT "CK_Sol_Cantidades" CHECK ("CantidadSolicitada" > 0
                                     AND ("CantidadOfrecida" IS NULL OR "CantidadOfrecida" >= 0)),
    CONSTRAINT "CK_Sol_Reintegrado" CHECK ("StockReintegrado" IN (0, 1)),

    -- Una solicitud sólo puede salir de PENDIENTE si ya trae cantidad.
    CONSTRAINT "CK_Sol_OfertaCoherente" CHECK
        ("Estado" = 'PENDIENTE' OR "CantidadOfrecida" IS NOT NULL)
);

/* Bandeja de Central: "todo lo que está esperando respuesta mía". */
CREATE INDEX IF NOT EXISTS "IX_Sol_Estado"
    ON dbo."SolicitudesStock" ("Estado", "FechaSolicitud")
    INCLUDE ("SucursalID", "ProductoID", "CantidadSolicitada", "CantidadOfrecida");

/* Bandeja de la sucursal. */
CREATE INDEX IF NOT EXISTS "IX_Sol_Sucursal"
    ON dbo."SolicitudesStock" ("SucursalID", "Estado", "FechaSolicitud");

/* Impide que la alerta automática genere una solicitud nueva cada vez
   que se vende una pieza estando ya bajo el mínimo. Es único sólo entre
   solicitudes ABIERTAS, así que el histórico sí puede repetirse.
   Distintas sucursales nunca chocan aquí porque SucursalID va incluido.

   En SQL Server esto era un índice FILTRADO y obligaba a QUOTED_IDENTIFIER
   ON en toda sesión que escribiera la tabla. En Postgres el índice parcial
   no impone nada al cliente: la advertencia operativa desaparece. */
CREATE UNIQUE INDEX IF NOT EXISTS "UX_Sol_AbiertaPorProducto"
    ON dbo."SolicitudesStock" ("SucursalID", "ProductoID")
    WHERE "Estado" IN ('PENDIENTE', 'OFERTADO');


/* =====================================================================
   PARTE 4 — BITÁCORAS Y OPERACIÓN
   ===================================================================== */

/* ---------------------------------------------------------------------
   Movimientos — bitácora única de todo lo que mueve stock.
   Es la que permite auditar por qué un número cambió.
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo."Movimientos"
(
    "MovimientoID"     INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ProductoID"       INTEGER       NOT NULL,
    "TipoMovimiento"   VARCHAR(20)   NOT NULL,
    "Cantidad"         INTEGER       NOT NULL,
    "SucursalOrigen"   INTEGER           NULL,   -- NULL = viene del proveedor
    "SucursalDestino"  INTEGER           NULL,   -- NULL = salió por venta
    "EmpleadoID"       INTEGER           NULL,
    "Referencia"       VARCHAR(200)      NULL,
    "Fecha"            TIMESTAMP(0)  NOT NULL DEFAULT dbo.ahora(),

    CONSTRAINT "PK_Movimientos"    PRIMARY KEY ("MovimientoID"),
    CONSTRAINT "FK_Mov_Producto"   FOREIGN KEY ("ProductoID")
        REFERENCES dbo."Productos" ("ProductoID"),
    CONSTRAINT "FK_Mov_SucOrigen"  FOREIGN KEY ("SucursalOrigen")
        REFERENCES dbo."Sucursales" ("SucursalID"),
    CONSTRAINT "FK_Mov_SucDestino" FOREIGN KEY ("SucursalDestino")
        REFERENCES dbo."Sucursales" ("SucursalID"),
    CONSTRAINT "FK_Mov_Empleado"   FOREIGN KEY ("EmpleadoID")
        REFERENCES dbo."Empleados" ("EmpleadoID"),
    CONSTRAINT "CK_Mov_Tipo"       CHECK ("TipoMovimiento" IN
        ('Entrada', 'Salida', 'Venta', 'Transferencia', 'Ajuste')),
    CONSTRAINT "CK_Mov_Cantidad"   CHECK ("Cantidad" > 0)
);

CREATE INDEX IF NOT EXISTS "IX_Mov_Producto" ON dbo."Movimientos" ("ProductoID", "Fecha" DESC);
CREATE INDEX IF NOT EXISTS "IX_Mov_Fecha"    ON dbo."Movimientos" ("Fecha" DESC);


/* ---------------------------------------------------------------------
   Ventas / DetalleVenta — punto de venta de las sucursales.

   "SucursalID" es obligatoria: sin ella no se puede saber de qué almacén
   salió la mercancía. En SQL Server esta columna se agregó a posteriori
   (script 10, PARTE 3.1); aquí nace con la tabla.
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo."Ventas"
(
    "VentaID"     INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Fecha"       TIMESTAMP(0)   NOT NULL DEFAULT dbo.ahora(),
    "EmpleadoID"  INTEGER            NULL,
    "Total"       NUMERIC(18,2)  NOT NULL DEFAULT 0,
    "SucursalID"  INTEGER        NOT NULL,

    CONSTRAINT "PK_Ventas"         PRIMARY KEY ("VentaID"),
    CONSTRAINT "FK_Ventas_Empleado" FOREIGN KEY ("EmpleadoID")
        REFERENCES dbo."Empleados" ("EmpleadoID"),
    CONSTRAINT "FK_Ventas_Sucursal" FOREIGN KEY ("SucursalID")
        REFERENCES dbo."Sucursales" ("SucursalID"),
    CONSTRAINT "CK_Ventas_Total"   CHECK ("Total" >= 0)
);

CREATE INDEX IF NOT EXISTS "IX_Ventas_Sucursal_Fecha"
    ON dbo."Ventas" ("SucursalID", "Fecha" DESC);


CREATE TABLE IF NOT EXISTS dbo."DetalleVenta"
(
    "DetalleVentaID"  INTEGER        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "VentaID"         INTEGER        NOT NULL,
    "ProductoID"      INTEGER        NOT NULL,
    "Cantidad"        INTEGER        NOT NULL,
    "PrecioUnitario"  NUMERIC(18,2)  NOT NULL,

    CONSTRAINT "PK_DetalleVenta"    PRIMARY KEY ("DetalleVentaID"),
    CONSTRAINT "FK_Det_Venta"       FOREIGN KEY ("VentaID")
        REFERENCES dbo."Ventas" ("VentaID") ON DELETE CASCADE,
    CONSTRAINT "FK_Det_Producto"    FOREIGN KEY ("ProductoID")
        REFERENCES dbo."Productos" ("ProductoID"),
    CONSTRAINT "CK_Det_Cantidad"    CHECK ("Cantidad" > 0),
    CONSTRAINT "CK_Det_Precio"      CHECK ("PrecioUnitario" >= 0)
);

CREATE INDEX IF NOT EXISTS "IX_Det_Venta" ON dbo."DetalleVenta" ("VentaID");


/* ---------------------------------------------------------------------
   Transferencias — el viaje físico de la mercancía Central -> sucursal.
   "SolicitudID" la enlaza con la requisición que la originó.
   --------------------------------------------------------------------- */
CREATE TABLE IF NOT EXISTS dbo."Transferencias"
(
    "TransferenciaID"  INTEGER       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ProductoID"       INTEGER       NOT NULL,
    "Cantidad"         INTEGER       NOT NULL,
    "SucursalOrigen"   INTEGER       NOT NULL,
    "SucursalDestino"  INTEGER       NOT NULL,
    "Estado"           VARCHAR(20)   NOT NULL DEFAULT 'Pendiente',
    "EmpleadoID"       INTEGER           NULL,
    "Fecha"            TIMESTAMP(0)  NOT NULL DEFAULT dbo.ahora(),
    "SolicitudID"      INTEGER           NULL,

    CONSTRAINT "PK_Transferencias"    PRIMARY KEY ("TransferenciaID"),
    CONSTRAINT "FK_Tra_Producto"      FOREIGN KEY ("ProductoID")
        REFERENCES dbo."Productos" ("ProductoID"),
    CONSTRAINT "FK_Tra_SucOrigen"     FOREIGN KEY ("SucursalOrigen")
        REFERENCES dbo."Sucursales" ("SucursalID"),
    CONSTRAINT "FK_Tra_SucDestino"    FOREIGN KEY ("SucursalDestino")
        REFERENCES dbo."Sucursales" ("SucursalID"),
    CONSTRAINT "FK_Tra_Empleado"      FOREIGN KEY ("EmpleadoID")
        REFERENCES dbo."Empleados" ("EmpleadoID"),
    CONSTRAINT "FK_Tra_Solicitud"     FOREIGN KEY ("SolicitudID")
        REFERENCES dbo."SolicitudesStock" ("SolicitudID"),
    CONSTRAINT "CK_Tra_Estado"        CHECK ("Estado" IN ('Pendiente', 'Completada', 'Rechazada')),
    CONSTRAINT "CK_Tra_Cantidad"      CHECK ("Cantidad" > 0),
    CONSTRAINT "CK_Tra_Sedes"         CHECK ("SucursalOrigen" <> "SucursalDestino")
);

CREATE INDEX IF NOT EXISTS "IX_Tra_Solicitud" ON dbo."Transferencias" ("SolicitudID");
CREATE INDEX IF NOT EXISTS "IX_Tra_Estado"    ON dbo."Transferencias" ("Estado", "Fecha" DESC);


/* =====================================================================
   PARTE 5 — VISTAS
   ===================================================================== */

CREATE OR REPLACE VIEW dbo."vw_StockPorSucursal" AS
    SELECT  inv."SucursalID",
            s."Nombre"              AS "Sucursal",
            inv."ProductoID",
            p."Nombre"              AS "Producto",
            c."Nombre"              AS "Categoria",
            p."Marca",
            p."TipoMascota",
            p."PrecioUnitario",
            p."Activo"              AS "ProductoActivo",
            inv."Stock",
            inv."StockMinimo",
            inv."StockObjetivo",
            inv."UltimaActualizacion",
            CASE WHEN inv."Stock" <= inv."StockMinimo" THEN 1 ELSE 0 END AS "EnAlerta"
      FROM  dbo."InventarioSucursal" inv
      JOIN  dbo."Sucursales" s ON s."SucursalID"  = inv."SucursalID"
      JOIN  dbo."Productos"  p ON p."ProductoID"  = inv."ProductoID"
      JOIN  dbo."Categorias" c ON c."CategoriaID" = p."CategoriaID";


/* Panorama que usa Central: stock propio vs. repartido en la red. */
CREATE OR REPLACE VIEW dbo."vw_StockGlobal" AS
    SELECT  p."ProductoID",
            p."Nombre"  AS "Producto",
            p."Activo",
            SUM(CASE WHEN s."EsCentral" = 1 THEN inv."Stock" ELSE 0 END) AS "StockCentral",
            SUM(CASE WHEN s."EsCentral" = 0 THEN inv."Stock" ELSE 0 END) AS "StockSucursales",
            SUM(inv."Stock")                                             AS "StockTotal"
      FROM  dbo."Productos" p
      JOIN  dbo."InventarioSucursal" inv ON inv."ProductoID" = p."ProductoID"
      JOIN  dbo."Sucursales" s           ON s."SucursalID"   = inv."SucursalID"
     GROUP BY p."ProductoID", p."Nombre", p."Activo";


DO $$ BEGIN
    RAISE NOTICE '=====================================================';
    RAISE NOTICE ' [OK] Esquema creado.';
    RAISE NOTICE ' Siguiente paso: 02_funciones_y_trigger.sql';
    RAISE NOTICE '=====================================================';
END $$;
